// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event_store/protos/eventstore.proto

package event_store_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId          string   `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventData            string   `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	Channel              string   `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_294f1175bd1b6bb5, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func (m *Event) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type CreateEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_294f1175bd1b6bb5, []int{1}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_294f1175bd1b6bb5, []int{2}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *CreateEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetEventsRequest struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AggregateId          string   `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_294f1175bd1b6bb5, []int{3}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *GetEventsRequest) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_294f1175bd1b6bb5, []int{4}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event_store.Event")
	proto.RegisterType((*CreateEventRequest)(nil), "event_store.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "event_store.CreateEventResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "event_store.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "event_store.GetEventsResponse")
}

func init() {
	proto.RegisterFile("event_store/protos/eventstore.proto", fileDescriptor_294f1175bd1b6bb5)
}

var fileDescriptor_294f1175bd1b6bb5 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6b, 0xe2, 0x50,
	0x14, 0x9d, 0xe8, 0x44, 0xcd, 0xcd, 0x8c, 0xe8, 0x9d, 0x59, 0x64, 0x04, 0xa7, 0x36, 0xa5, 0x20,
	0x5d, 0x28, 0xd8, 0x7d, 0x0b, 0xfd, 0xa0, 0x58, 0xba, 0x28, 0xb1, 0xab, 0x6e, 0xe4, 0x99, 0x5c,
	0x6c, 0xa0, 0x24, 0xe9, 0x7b, 0x4f, 0xc1, 0x1f, 0xd6, 0x7f, 0xd0, 0x1f, 0x56, 0xbc, 0x2f, 0xa6,
	0x51, 0xb1, 0xcb, 0x7b, 0xee, 0xb9, 0x27, 0xe7, 0x9c, 0x17, 0x38, 0xa1, 0x25, 0x25, 0x7a, 0xaa,
	0x74, 0x2a, 0x69, 0x98, 0xc9, 0x54, 0xa7, 0x6a, 0xc8, 0x10, 0x23, 0x03, 0x46, 0xd0, 0x2d, 0x91,
	0xfc, 0x0f, 0x0b, 0xec, 0xdb, 0xf5, 0x8c, 0xff, 0xa0, 0x61, 0x16, 0x71, 0xe4, 0x59, 0x3d, 0xab,
	0xef, 0x04, 0x75, 0x9e, 0xc7, 0x11, 0x76, 0x01, 0xcc, 0x4a, 0xaf, 0x32, 0xf2, 0x2a, 0xbc, 0x74,
	0x18, 0x79, 0x5a, 0x65, 0x84, 0xc7, 0xf0, 0x4b, 0xcc, 0xe7, 0x92, 0xe6, 0x42, 0xd3, 0xfa, 0xba,
	0xca, 0x04, 0xb7, 0xc0, 0xc6, 0x11, 0x9e, 0x42, 0xf3, 0x8b, 0xc2, 0x2a, 0x3f, 0x99, 0xf4, 0xbb,
	0x40, 0x59, 0xa9, 0xf8, 0x50, 0x24, 0xb4, 0xf0, 0xec, 0xd2, 0x87, 0x6e, 0x84, 0x16, 0xe8, 0x41,
	0x3d, 0x7c, 0x11, 0x49, 0x42, 0xaf, 0x5e, 0xcd, 0x38, 0xcc, 0x47, 0xff, 0x02, 0xf0, 0x5a, 0x92,
	0xd0, 0xc4, 0x59, 0x02, 0x7a, 0x5b, 0x90, 0xd2, 0xd8, 0x07, 0x9b, 0x8f, 0x39, 0x8f, 0x3b, 0xc2,
	0x41, 0x29, 0xf9, 0xc0, 0x30, 0x0d, 0xc1, 0xbf, 0x87, 0x3f, 0x5b, 0xf7, 0x2a, 0x4b, 0x13, 0xc5,
	0x7e, 0x62, 0x35, 0x55, 0x8b, 0x30, 0x24, 0xa5, 0x58, 0xa5, 0x11, 0x38, 0xb1, 0x9a, 0x18, 0x00,
	0xff, 0x82, 0x4d, 0x52, 0xa6, 0x32, 0xaf, 0xc4, 0x0c, 0xfe, 0x23, 0xb4, 0xee, 0x48, 0xb3, 0x90,
	0xda, 0x38, 0xf9, 0xa6, 0xdc, 0xdd, 0xf6, 0x2a, 0x7b, 0xed, 0xf9, 0x97, 0xd0, 0x2e, 0x29, 0xe6,
	0xde, 0xce, 0xa0, 0x66, 0x9e, 0xd6, 0xb3, 0x7a, 0xd5, 0x03, 0xe9, 0x72, 0xc6, 0xe8, 0xdd, 0x82,
	0x36, 0x23, 0x93, 0xf5, 0x72, 0x42, 0x72, 0x19, 0x87, 0x84, 0x0f, 0xe0, 0x14, 0xb2, 0xd8, 0xdd,
	0x3a, 0xdf, 0x0d, 0xd0, 0xf9, 0x7f, 0x68, 0x6d, 0xdc, 0xf8, 0x3f, 0x30, 0x00, 0xb7, 0x54, 0x21,
	0x1e, 0x6d, 0x1d, 0xec, 0x3f, 0x4e, 0xa7, 0x77, 0x98, 0xb0, 0xd1, 0xbc, 0x6a, 0x3d, 0x37, 0x4b,
	0xa4, 0x69, 0x36, 0x9b, 0xd5, 0xf8, 0x1f, 0x3e, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xff,
	0x19, 0x6c, 0xea, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreServiceClient is the client API for EventStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreServiceClient interface {
	// Get all events for the given aggregate and event
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Create a new event to the event store
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
}

type eventStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreServiceClient(cc *grpc.ClientConn) EventStoreServiceClient {
	return &eventStoreServiceClient{cc}
}

func (c *eventStoreServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/event_store.EventStoreService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/event_store.EventStoreService/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServiceServer is the server API for EventStoreService service.
type EventStoreServiceServer interface {
	// Get all events for the given aggregate and event
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Create a new event to the event store
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
}

// UnimplementedEventStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventStoreServiceServer struct {
}

func (*UnimplementedEventStoreServiceServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedEventStoreServiceServer) CreateEvent(ctx context.Context, req *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}

func RegisterEventStoreServiceServer(s *grpc.Server, srv EventStoreServiceServer) {
	s.RegisterService(&_EventStoreService_serviceDesc, srv)
}

func _EventStoreService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_store.EventStoreService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStoreService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_store.EventStoreService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event_store.EventStoreService",
	HandlerType: (*EventStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _EventStoreService_GetEvents_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _EventStoreService_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event_store/protos/eventstore.proto",
}
